### ISSUE TITLE
[BUG] System messages don't seem to work

### ISSUE THREAD

**Issue by mmiddlezong** [Bin-Huang/chatbox#1309] opened 2024-04-22 23:28 UTC
**Bug Description**
When providing a system message stating "Only respond with the code. Do not provide an explanation unless it is specifically asked for," gpt-4-turbo still attempts to explain the code. **This contrasts with behavior obtained by calling the OpenAI API directly; in that case, gpt-4-turbo successfully avoids giving an explanation and only provides code.**

**Steps to Reproduce**
Please provide the steps to reproduce the bug:

0. Configure the app to use gpt-4-turbo on default settings
1. Click on "New Chat"
2. Edit the system message to: "Only respond with the code. Do not provide an explanation unless it is specifically asked for." or something similar.
3. Click SAVE.
4. Type in the message, "Give me React code for a login form"
5. Observe

**Expected Results**
The bot should respond with only the code, with brief or no explanation. This is the behavior seen with other chatbot GUIs and the OpenAI API itself.

**Actual Results**
The bot provides a lengthy explanation of the code.

**Screenshots**
<img width="1208" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/119022671/9bce3567-7466-41bd-94e8-49f7b0882988">
<img width="1170" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/119022671/18dc4ea8-ccb2-4ed1-b3be-610118975fe4">

**Desktop (please complete the following information):**

-   Operating System: macOS
-   Application Version: 1.3.5

**Comment by EarNugget** [comment] 2024-04-25 19:41
I have also unfortunately noticed system messages not working. It would be awesome to have it.

**Comment by mmiddlezong** [comment] 2024-04-26 12:13
Using the model `gpt-4` seems to have system messages working, but `gpt-4-turbo` does not.

**Comment by Bin-Huang** [comment] 2024-05-05 03:49
This was caused by a bug, which I have fixed in version 1.3.6.

**Closed by Bin-Huang** 2024-05-05 03:49 UTC
