### ISSUE TITLE
[BUG] Claude API - "invalid_request_error", first message must use the "user" role.

### ISSUE THREAD

**Issue by TBS-CL** [Bin-Huang/chatbox#1288] opened 2024-04-11 12:38 UTC
**Bug Description**
Chats with use of Claude API (sonnet model) return errors 400:
```
An error has occurred with Claude, which is usually caused by incorrect settings or account issues. Please check your AI settings and account status, or [click here to view the FAQ document](https://chatboxai.app/redirect_app/faqs/en).

API Error: Status Code 400, {"type":"error","error":{"type":"invalid_request_error","message":"messages: first message must use the \"user\" role"}}
```

The initial message is set like usual:
![image](https://github.com/Bin-Huang/chatbox/assets/80581735/82d271a4-d6cc-4963-9125-d330d591bf71)

**Steps to Reproduce**
Start new Claude chat (sonnet / opus / haiku), if it works initially, try deleting some messages from context, and keep prompting until you see an error.

**Desktop (please complete the following information):**

-   Operating System: `Windows 11 23H2`
-   Application Version: `1.3.3`

**Comment by Bin-Huang** [comment] 2024-04-15 06:23
Fixed in v1.3.4

**Closed by Bin-Huang** 2024-04-15 06:23 UTC

**Comment by lincbal4** [comment] 2024-10-20 15:22
Having this exact same issue on 1.5.1

**Comment by lenguyenhcm325** [comment] 2024-12-07 15:22
> Having this exact same issue on 1.5.1

Me too, really frustrating and costed more tokens than expected because constant retries are needed.

**Comment by Bin-Huang** [comment] 2024-12-08 10:44
@lenguyenhcm325  Usually errors don't actually consume tokens. What error message you're getting? That would help me understand what's going on.

**Comment by lenguyenhcm325** [comment] 2024-12-08 10:59
> @lenguyenhcm325 Usually errors don't actually consume tokens. What error message you're getting? That would help me understand what's going on.

It's the `overloaded_error` as defined right here: https://docs.anthropic.com/en/api/errors

I think that's somewhat clear enough, when I am able to reproduce the error, I will give you the whole JSON String.

I got this error usually when I started the Chatbox app on my Windows 11, after the first 5 - 10 questions it stopped happening.

I didn't know that error doesn't cost token, thank you for that!

**Comment by Bin-Huang** [comment] 2024-12-08 11:31
> > @lenguyenhcm325 Usually errors don't actually consume tokens. What error message you're getting? That would help me understand what's going on.
> 
> It's the `overloaded_error` as defined right here: https://docs.anthropic.com/en/api/errors
> 
> I think that's somewhat clear enough, when I am able to reproduce the error, I will give you the whole JSON String.
> 
> I got this error usually when I started the Chatbox app on my Windows 11, after the first 5 - 10 questions it stopped happening.
> 
> I didn't know that error doesn't cost token, thank you for that!

If it's indeed the overloaded_error, according to Claude's official docs, this usually happens when Claude's servers are temporarily unavailable or overloaded. It's not really related to client apps like Chatbox - it's more of a server-side issue from Claude itself.
